Feature/solidify receipt initialization
nomad/venice pull request #77
Opened 2019-02-25 07:43 UTC by pirvudoru

This is to be able to initialize receipt from response without any additional processing outside the constructor.

2019-09-21 19:22 UTC, dankimio commented on lib/venice/client.rb
> +    attr_accessor :verification_url, :env_name
Could we call this just environment?

2019-09-21 19:23 UTC, dankimio requested changes

2019-09-21 19:23 UTC, dankimio commented on spec/receipt_spec.rb
> +                'status' => 21007,
Indentation is off.

2019-09-21 19:25 UTC, dankimio commented on lib/venice/receipt.rb
> +    module EnvName
Why did we move this module to `Receipt`? Can we extract `Environment` module into the root scope? It's still used in multiple places.

2020-09-18 06:12 UTC, pirvudoru commented
Closed as included in https://github.com/nomad/venice/pull/79 which was merged. 

Missed the review :( sorry.

2020-09-18 06:12 UTC, closed without merging